### ISSUE TITLE
Hover-over highlighting is only momentary

### ISSUE THREAD

**Issue by LaurenceMolloy** [anntzer/mplcursors#21]
I’m having trouble keeping the boxes highlighted while hovering over them. Unless I remove my finger from the mousepad or (with a mouse attached) stop moving the mouse the moment the mouse pointer touches the bar the highlight only lasts momentarily.

Minimal working code example below (using border highlight only) that exhibits this behaviour for me.

    import matplotlib.pyplot as plt
    import mplcursors

    fig, ax = plt.subplots()
    ax.bar(range(9), range(1, 10), align="center")

    cursor = mplcursors.cursor(hover=True)

    @cursor.connect("add")
    def on_add(sel):
        x, y, width, height = sel.artist[sel.target.index].get_bbox().bounds
        sel.annotation.set(text=f"{x+width/2}: {height}", position=(0, 5))
        sel.annotation.xy = (x + width / 2, y + height)
        sel.artist[sel.target.index].set_edgecolor('r')

    @cursor.connect("remove")
    def on_remove(sel):
        sel.artist[sel.target.index].set_edgecolor('w')

    plt.show()

**Comment from @anntzer** 

_Almost certainly this is because the highlighting code shares basically all event handling with the annotation code, but they should likely be slightly split so that the highlight doesn’t get removed until the cursor goes away._

**Comment by anntzer** [comment]
As it turns out, this is not so easy to fix.  (I had initially missed the fact that you were using your own highlighting callbacks, I guess because I don't support highlighting by default for BarContainers?  This could be fixed too...)

Basically, what happens when you move the cursor a tiny bit (in hovering mode) is that the annotation gets removed and another annotation get added -- but actually the order in which things happen is that the new annotation is added *first* and then the old annotation is removed.  I had done this specifically because at some point I wanted to be able to have the "add" callback (called on the new annotation) undo the addition of the new callback (immediately remove()ing it) and keep the old annotation instead.  Plus I think this helps with some blitting optimizations, although that's from my own comments of a few years ago and I'm not really sure anymore what was the concrete need on that side.  So in your case on_add gets called *first* and on_remove gets called *after*, undoing the highlight.  I guess the call order (which I mostly considered to be an implementation detail) has effectively become part of the API contract :(  I'm not sure what the best solution is -- document the callback call order? try to remove() before add()ing?

In the meantime you can fix your exact use case by restoring the relevant highlights also in on_remove()
```python
@cursor.connect("remove")
def on_remove(sel):
    sel.artist[sel.target.index].set_edgecolor('w')
    for sel in cursor.selections:
        sel.artist[sel.target.index].set_edgecolor('r')
```
which is a bit ugly but seems to work for me.

**Comment by LaurenceMolloy** [comment]
Perfect (for now). I can live with ugly mplcursors code. There are far bigger issues that I need to address in my code anyway. ;) Thanks Anthony.

**Comment by anntzer** [comment]
I went for the easy route of just documenting the call order ("add" before "remove") for now.

**Comment by LaurenceMolloy** [comment]
👍😁
