### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by jorgesmok** [anntzer/mplcursors#22]
Hello,

Two years ago I worked on a project on which I used a master version of mplcursors, it was after 0.1 and before 0.2, specifically "0.1+60.g96d4cf6". Now I'm trying to edit something in my code and I'm trying to download mplcursors again but I can't install version 0.2/0.3 because they demand python >= 3.6 (can't use that version due to other package restriction). Version 0.1 works on python 3.5 but it doesn't have a functionality I need: remove_selection. Can you see a workaround for this? Maybe retrieve version 0.1+60.g96d4cf6, or somehow make 0.2 compatible with python 3.5. 

Regards.

**Comment by anntzer** [comment]
v0.2 should be compatible with Py3.5 (even Py3.4), it what aspect does it not work for you?
If you want to recuperate the specific commit it's 60 commits after v0.1 which is now 1d72955 (due to history edits); you can install it using `pip install git+https://github.com/anntzer/mplcursors.git@1d72955`.

PS: I am trying to build a list of users of mplcusors (see end of the current readme); I would be happy to know more about your use case :)

**Comment by jorgesmok** [comment]
Ok it's solved, I could install v0.2 yesterday. I don't know what was the problem, I think it was master version which didn't let me install on python 3.5, I can verify later when I arrive home.

**Comment by jorgesmok** [comment]
The program is for design and analysis of antenna theory, I will try to upload it somewhere and I'll let you know, I'd like to be on that list.

**Comment by anntzer** [comment]
Master is indeed incompatible with Py3.5 (but mostly it depends on matplotlib>=3.1, which is incompatible with Py3.5...).

**Comment by jorgesmok** [comment]
Yes, that was it, I'm also using an older version of matplotlib.

**Comment by jorgesmok** [comment]
Btw, is any version of mplcursors compatible with python 2?

**Comment by anntzer** [comment]
No, mplcursors (like all my personal projects since many years ago, for that matter...) was Py3-only from the very beginning.

**Comment by anntzer** [comment]
I'll close this as fixed?
