### ISSUE TITLE
On floating bar chart, x-position behavior is inaccurate 

### ISSUE THREAD

**Issue by jeetsukumaran** [anntzer/mplcursors#42]
The y-position seems accurate, but the x-position does not seem to work correctly. It seems to hit a fixed spot along the axis, regardless of where you click. For example, it's impossible to get a position at the beginning or end of the bar.

~~~python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import matplotlib.pyplot as plt
import mplcursors
import random

def main():

    yvals = list("abcdefghijklmnopqrstuvwxyz")
    starts = []
    ends = []
    for y in yvals:
        start = random.randint(1, 1000)
        end = start + random.randint(500, 1000)
        starts.append(start)
        ends.append(end)

    fig, ax = plt.subplots()
    ax.barh(width=ends, left=starts, height=1.0, y=yvals)

    cursor = mplcursors.cursor(hover=True)
    @cursor.connect("add")
    def on_add(sel):
        x, y, width, height = sel.artist[sel.target.index].get_bbox().bounds
        sel.annotation.set(text=f"{yvals[round(y)]}: position {round(x+width/2)}",
                        position=(0, 20), anncoords="offset points")
        sel.annotation.xy = (x + width / 2, y + height)

    plt.show()

if __name__ == '__main__':
    main()
~~~

**Comment by anntzer** [comment]
OK, I see.  This is because the bars are still interpreted as being a horizontal histogram (this is why there is no margin to the left of the leftmost bar); this interpretation is controlled by sticky_edges (https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/axes_margins.html).  The short term fix for you would be to remove the sticky edge, i.e.
```python
    bars = ax.barh(width=ends, left=starts, height=1.0, y=yvals)
    for patch in bars:
        patch.sticky_edges.x[:] = []
```

Perhaps matplotlib should not set sticky edges if the bars have different bases, but I'd say that's something to argue on the Matplotlib tracker instead.

**Comment by jeetsukumaran** [comment]
Thanks! 

That works perfectly!

![Peek 2021-10-29 13-06](https://user-images.githubusercontent.com/26183/139495660-69d779d9-8e95-4760-8e97-74be4ac3bc27.gif)

Appreciate your advice ... and this great module!
