### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'points_to_pixels'

### ISSUE THREAD

**Issue by nilswagner** [anntzer/mplcursors#9]
Run change_popup_color.py and click into the left figure (No box, different position)

**Comment by anntzer** [comment]
Thanks, I had noticed this in 10a3602bd20b5e5a25a5cdbecf9f6f834b579da3.
This is a bug in Matplotlib 3.0 (as noted in that commit; fixed in https://github.com/matplotlib/matplotlib/pull/12164); I'm going to wait for mpl3.0.1 to be released and update mplcursors to exclude mpl==3.0.0, as I think it's a relatively rare case anyways (explicitly not drawing the box) and I don't think there's a simple fix on mplcursors' side.
